config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :banks
  resources :branches
  resources :employee_teams
  resources :teams do
    get :selected, on: :member
  end

  resources :demo_schedules
  resources :transmittals do
    get :remove_or, on: :member
  end

  resources :special_arrangements
  resources :sip_pbs
  resources :sip_abs
  resources :koopamilya_pbs
  resources :koopamilya_abs
  resources :reinsurance_members
  resources :reinsurer_ri_batches
  resources :reinsurers
  resources :claim_request_for_payments
  resources :claim_payments
  get "actuarial/index"

  namespace :actuarial do
    resources :reserves
    resources :reserve_batches
  end

  resources :group_proposals
  resources :unit_benefits
  resources :plan_units do
    get :find_units, on: :member
  end
  resources :reinsurances do
    get :reserves_index, on: :collection
  end
  namespace :claims do
    resources :claim_types, :claim_documents, :claim_type_benefits, :claim_confinements, :claim_benefits, :claim_coverages, :claim_distributions, :claim_type_natures, :claim_type_agreements, :claim_retrievals

    resources :cf_accounts do
      get :index_critical, to: "cf_accounts#index_critical", on: :collection
    end

    resources :cf_replenishes do
      get :update_status, to: "cf_replenishes#update_status", on: :member
    end
    resources :cf_availments do
      get :update_status, to: "cf_availments#update_status", on: :member
    end
    resources :claim_coverage_reinsurances do
      get :claim_reinsurance_create, to: "claim_coverage_reinsurances#claim_reinsurance_create", as: "claim_ri_create", on: :collection
      get :claim_reinsurance_update, to: "claim_coverage_reinsurances#claim_reinsurance_update", as: "claim_ri_update", on: :member
    end

    resources :causes do
      post 'create_cause', to: "causes#create"
    end
    resources :claim_attachments do
      get :attach_new_doc, on: :collection
    end

    resources :claim_type_documents do
      get :document_request, to: "claim_type_documents#document_request", on: :member
    end

    resources :process_claims do
      get :new_coop, to: "process_claims#new_coop", on: :collection
      post :create_coop, to: "process_claims#create_coop", on: :collection
      get :index_coop, to: "process_claims#index_coop", on: :collection
      get :index_show, on: :collection
      get :index_claim_type, on: :collection
      get :show_coop, on: :member
      get :claim_route, on: :member
      get :claims_file, on: :member
      get :claim_process, on: :member
      get :update_status, on: :member
      get :new_ca, to: "process_claims#new_ca", on: :collection
      get :edit_ca, to: "process_claims#edit_ca", on: :member
      get :edit_coop, to: "process_claims#edit_coop", on: :member
      post :create_ca, to: "process_claims#create_ca", on: :collection
      patch :update_ca, to: "process_claims#update_ca", on: :member
      patch :update_coop, to: "process_claims#update_coop", on: :member
      get :print_sheet, to: "process_claims#print_sheet", on: :member
      get :claims_dashboard, to: "process_claims#claims_dashboard", on: :collection
      get :approve_claim_debit, on: :member
      # get :claimable, on: :collection
      resources :remarks
    end

    resources :claim_remarks do
      get :new_status, to: "claim_remarks#new_status", on: :collection
      post :create_status, to: "claim_remarks#create_status", on: :collection
      get :message_history, to: "claim_remarks#message_history", on: :collection
      get :read_message, on: :member
      get :unread_messages, on: :collection
    end
  end




  resources :documents
  resources :emp_approvers
  get "med_directors/home"
  get "med_director/index"

  resources :emp_agreements do
    get :transfer_index, on: :collection
    get :update_ea_selected, on: :collection
    patch :transfer_agreements, on: :collection
    get :inactive_sub, on: :member
  end
  # resources :denied_dependents

  resources :anniversaries, :agent_groups, :departments, :agents, :coop_users, :employees, :product_benefits

  resources :plans do
    get :selected, on: :member
    get :show_rates, on: :member
    get :show_fields, on: :member
  end

  resources :dashboards do
    get :actuarial, on: :collection
    get :claims, on: :collection
    get :mis, on: :collection
    get :coop, on: :collection
    get :treasury, on: :collection
    get :accounting, on: :collection
    get :admin, on: :collection
  end
  
  resources :analytics do 
    get :claims, on: :collection
  end

  resources :user do
    get :approved, on: :member
    get :admin_dashboard, on: :collection
  end

  resources :agreement_benefits do
    get :selected, on: :member
  end

  resources :agreements do
    get :show_details, on: :member
    post :update_ors, on: :member
    get :selected, on: :member
  end

  # resources :agreement_benefits
  # resources :plans
  # resources :agreements
  # resources :cooperatives
  resources :coop_types
  resources :geo_barangays

  resources :geo_municipalities do
    get :selected, on: :member
  end

  resources :geo_provinces do
    get :selected, on: :member
  end

  resources :geo_regions do
    get :selected, on: :member
  end
  # resources :agent_groups
  # resources :departments
  # resources :agents
  # resources :coop_users
  # resources :employees
  resources :benefits
  get 'pages/home'
  get 'pages/coso'
  get 'pages/president'
  get 'pages/coop'
  get 'pages/find_graph'
  get "update_charts", to: "pages#update_charts", as: "update_charts"
  get "select_charts", to: "pages#select_charts", as: "select_charts"
  get "update_prem_annum", to: "pages#update_prem_annum", as: "update_prem_annum"
  # get "/pages/modals/modal_charts", to: "pages#modal_charts", as: "modal_charts"
  get "modal_charts", to: "pages#modal_charts", as: "modal_charts"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/progress", to: "progress#show"
  get "/progress/update", to: "progress#update"

  # * Coop Module
  namespace :coop do
    get "dashboard", to: "dashboard#index"
  end

  resources :cooperatives do
    get :selected, on: :member
    get :select_agreement, on: :member
    get :details, on: :member
    get :get_plan, on: :member
  end
  resources :coop_banks
  resources :coop_branches

  resources :members do
    collection do
      post :import
    end
    get :show_coverages, on: :member
  end

  resources :coop_members do
    get :selected, on: :member
    get :member_agreements, on: :member
    get :show_insurance, on: :member
    get :find_member, on: :member
  end

  resources :denied_enrollees, only: [:index] do
    # routes for deleting all denied enrolle
    delete :destroy_all, on: :collection
  end

  resources :coop_agreements do
    resources :group_remits do

      resources :remittances, only: [:index]
    end
  end

  resources :group_remits do
    resources :remarks, controller: "group_remit/remarks"
    get "denied_members", to: "denied_members#index"
    get "download_csv", to: "denied_members#download_csv"
    delete "destroy_all", to: "denied_members#destroy_all"
    get :submit, on: :member
    get :renewal, on: :member
    resources :batches do
      get :health_dec, on: :member
      get :modal_remarks, on: :member
      collection do
        post :import
        get :approve_all
        get :all_health_decs
      end
      # get :approve_selected, on: :collection
      # get :approve_all, on: :collection
      resources :batch_health_decs, as: "health_declarations"
      resources :dependent_health_decs, as: "dep_health_declarations"
      resources :batch_dependents, as: "dependents" do
        get :health_dec, on: :member
        collection do
          get :show_all
        end
      end
      resources :batch_beneficiaries, as: "beneficiaries"
      resources :member_dependents do
        collection do
          post :create_beneficiary
          get :new_beneficiary
        end
      end
    end
  end

  resources :health_decs do
    resources :health_dec_subquestions
  end

  namespace :loan_insurance do
    resources :retentions
    resources :rates
    resources :loans
    resources :details
    resources :batches do
      get :remove_unused, on: :member
      get :terminate, on: :member
      get :modal_remarks, on: :member
      get :find_loan, on: :member
      get :adjusted, on: :member
      post :accept_adjustment, on: :member
      post :cancel_coverage, on: :member
      get :adjustments, on: :member
      collection do
        get :approve_all
      end

      member do
        get :show_unuse_batch, as: "unuse_batch"
      end

      collection do
        post :import
      end

    end

    resources :group_remits do
      get :submit, on: :member
      get :edit_or, on: :member
      get :sii_index, on: :collection
      get "lppi_summary", on: :member
    end

    resources :history, only: [:index]
  end

  # get 'loan_insurance', to: 'loan_insurance#index'
  get "insurance/accept", as: "accept_insurance"
  # get 'insurance/reject', as: 'reject_insurance'
  get "insurance/terminate", as: "terminate_insurance"

  # * Finance Module Routes
  # accounting
  namespace :accounting do
    resources :account_beginning_balances
    resources :debit_advices do
      get :new_receipt, on: :member
      post :upload_receipt, on: :member
      get :download, on: :member
    end

    resources :journals do
      get :download, on: :member
      get :for_approval_index, on: :collection
      # get :for_jv, on: :collection
      get :requests, on: :collection
    end

    resources :checks do
      # get :for_approval_index, on: :collection
      get :claimable, on: :member
      # get :cancel, on: :member
      resources :business_checks, as: 'business', except: [:index]
      get :requests, on: :collection
      resources :remarks
      get :download, on: :member
      get :print, on: :member
    end

app/models/employee_team.rb
class EmployeeTeam < ApplicationRecord
  belongs_to :employee
  belongs_to :team
end

app/controllers/employee_teams_controller.rb
class EmployeeTeamsController < ApplicationController
  before_action :set_employee_team, only: %i[ show edit update destroy ]

  # GET /employee_teams
  def index
    @employee_teams = EmployeeTeam.all
  end

  # GET /employee_teams/1
  def show
  end

  # GET /employee_teams/new
  def new
    @team = Team.find_by(id: params[:team]) if params[:team].present?
    @employee_team = EmployeeTeam.new
  end

  # GET /employee_teams/1/edit
  def edit
  end

  # POST /employee_teams
  def create
    @employee_team = EmployeeTeam.new(employee_team_params)

    if @employee_team.save
      redirect_to @employee_team.team, notice: "Employee team was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employee_teams/1
  def update
    if @employee_team.update(employee_team_params)
      redirect_to @employee_team, notice: "Employee team was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /employee_teams/1
  def destroy
    @employee_team.destroy
    redirect_to employee_teams_url, notice: "Employee team was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_team
      @employee_team = EmployeeTeam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_team_params
      params.require(:employee_team).permit(:employee_id, :team_id, :head)
    end
end

app/views/employee_teams/_employee_team.html.erb
<div id="<%= dom_id employee_team %>">
  <p>
    <strong>Employee:</strong>
    <%= employee_team.employee_id %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= employee_team.team_id %>
  </p>

</div>

app/views/employee_teams/_form.html.erb
<%= simple_form_for(@employee_team) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-3">
    
    <% if @team.present? %>
      <%= f.input :team, input_html: {value: @team}, disabled: true %>
      <%= f.association :team, as: :hidden, input_html: {value: @team.id} %>
    <% else %>
      <%= f.association :team %>
    <% end %>
    <%= f.association :employee, label_method: :emp_email, input_html: { data: { controller: "ts--select" } } %>
    <%= f.input :head %>
  </div>

  <div class="form-actions text-end">
    <%= link_to "Back", employee_teams_path, class: 'btn btn-secondary' %>
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/employee_teams/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/employee_teams/edit.html.erb
<div class="card">
  <h5 class="card-header">Edit employee team</h5>
  <div class="card-body">
    <%= render "form", employee_team: @employee_team %>
  </div>
</div>

app/views/employee_teams/index.html.erb
<%= content_tag :h1, "List of Employee Teams" %>


<div class="text-end mb-3">
  <%= link_to new_employee_team_path, class: 'btn btn-primary' do %>
    New Employee Team
  <% end %>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
      <th>#</th>
            <th>Employee</th>
            <th>Team</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
      <% @employee_teams.each do |employee_team| %>
        <tr>

        <th scope="row"><%= employee_team.id %></th>
        <td><%= employee_team.employee %></td>
        <td><%= employee_team.team %></td>
    
          <td>
            <%= link_to 'View', employee_team, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_employee_team_path(employee_team), class: 'btn btn-secondary btn-sm' %>
            <%= link_to "Delete", employee_team, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/employee_teams/new.html.erb
<% if @team.present? %>
  <%= render "remote_modal", title: "New anniversary" do %>
    <%= render "form", employee_team: @employee_team %>
  <% end %>
<% else %>
  <div class="card">
    <h5 class="card-header">New employee team</h5>
    <div class="card-body">
      <%= render "form", employee_team: @employee_team %>
    </div>
  </div>
<% end %>

app/views/employee_teams/show.html.erb
<%= render @employee_team %>

<div>
  <%= link_to "Edit", edit_employee_team_path(@employee_team), class: 'btn btn-primary' %> |
  <%= link_to "Back", employee_teams_path, class: 'btn btn-primary' %>

  <%= button_to "Delete", @employee_team, method: :delete, class: 'btn btn-danger' %>
</div>