config/routes.rb
  resources :reinsurances do
    get :reserves_index, on: :collection
  end
  namespace :claims do
    resources :claim_types, :claim_documents, :claim_type_benefits, :claim_confinements, :claim_benefits, :claim_coverages, :claim_distributions, :claim_type_natures, :claim_type_agreements, :claim_retrievals

    resources :cf_accounts do
      get :index_critical, to: "cf_accounts#index_critical", on: :collection
    end

    resources :cf_replenishes do
      get :update_status, to: "cf_replenishes#update_status", on: :member
    end
    resources :cf_availments do
      get :update_status, to: "cf_availments#update_status", on: :member
    end
    resources :claim_coverage_reinsurances do
      get :claim_reinsurance_create, to: "claim_coverage_reinsurances#claim_reinsurance_create", as: "claim_ri_create", on: :collection
      get :claim_reinsurance_update, to: "claim_coverage_reinsurances#claim_reinsurance_update", as: "claim_ri_update", on: :member
    end

    resources :causes do
      post 'create_cause', to: "causes#create"
    end
    resources :claim_attachments do
      get :attach_new_doc, on: :collection
    end

    resources :claim_type_documents do
      get :document_request, to: "claim_type_documents#document_request", on: :member
    end

    resources :process_claims do
      get :new_coop, to: "process_claims#new_coop", on: :collection
      post :create_coop, to: "process_claims#create_coop", on: :collection
      get :index_coop, to: "process_claims#index_coop", on: :collection
      get :index_show, on: :collection
      get :index_claim_type, on: :collection
      get :show_coop, on: :member
      get :claim_route, on: :member
      get :claims_file, on: :member
      get :claim_process, on: :member
      get :update_status, on: :member
      get :new_ca, to: "process_claims#new_ca", on: :collection
      get :edit_ca, to: "process_claims#edit_ca", on: :member
      get :edit_coop, to: "process_claims#edit_coop", on: :member
      post :create_ca, to: "process_claims#create_ca", on: :collection
      patch :update_ca, to: "process_claims#update_ca", on: :member
      patch :update_coop, to: "process_claims#update_coop", on: :member
      get :print_sheet, to: "process_claims#print_sheet", on: :member
      get :claims_dashboard, to: "process_claims#claims_dashboard", on: :collection
      get :approve_claim_debit, on: :member
      # get :claimable, on: :collection
      resources :remarks
    end

    resources :claim_remarks do
      get :new_status, to: "claim_remarks#new_status", on: :collection
      post :create_status, to: "claim_remarks#create_status", on: :collection
      get :message_history, to: "claim_remarks#message_history", on: :collection
      get :read_message, on: :member
      get :unread_messages, on: :collection
    end
  end




  resources :documents
  resources :emp_approvers
  get "med_directors/home"
  get "med_director/index"

  resources :emp_agreements do
    get :transfer_index, on: :collection
    get :update_ea_selected, on: :collection
    patch :transfer_agreements, on: :collection
    get :inactive_sub, on: :member
  end
  # resources :denied_dependents

  resources :anniversaries, :agent_groups, :departments, :agents, :coop_users, :employees, :product_benefits

  resources :plans do
    get :selected, on: :member
    get :show_rates, on: :member
    get :show_fields, on: :member
  end

  resources :dashboards do
    get :actuarial, on: :collection
    get :claims, on: :collection
    get :mis, on: :collection
    get :coop, on: :collection
    get :treasury, on: :collection
    get :accounting, on: :collection
    get :admin, on: :collection
  end
  
  resources :analytics do 
    get :claims, on: :collection
  end

  resources :user do
    get :approved, on: :member
    get :admin_dashboard, on: :collection
  end

  resources :agreement_benefits do
    get :selected, on: :member
  end

  resources :agreements do
    get :show_details, on: :member
    post :update_ors, on: :member
    get :selected, on: :member
  end

  # resources :agreement_benefits
  # resources :plans
  # resources :agreements
  # resources :cooperatives
  resources :coop_types
  resources :geo_barangays

  resources :geo_municipalities do
    get :selected, on: :member
  end

  resources :geo_provinces do
    get :selected, on: :member
  end

  resources :geo_regions do
    get :selected, on: :member
  end
  # resources :agent_groups
  # resources :departments
  # resources :agents
  # resources :coop_users
  # resources :employees
  resources :benefits
  get 'pages/home'
  get 'pages/coso'
  get 'pages/president'
  get 'pages/coop'
  get 'pages/find_graph'
  get "update_charts", to: "pages#update_charts", as: "update_charts"
  get "select_charts", to: "pages#select_charts", as: "select_charts"
  get "update_prem_annum", to: "pages#update_prem_annum", as: "update_prem_annum"
  # get "/pages/modals/modal_charts", to: "pages#modal_charts", as: "modal_charts"
  get "modal_charts", to: "pages#modal_charts", as: "modal_charts"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/progress", to: "progress#show"
  get "/progress/update", to: "progress#update"

  # * Coop Module
  namespace :coop do
    get "dashboard", to: "dashboard#index"
  end

  resources :cooperatives do
    get :selected, on: :member
    get :select_agreement, on: :member
    get :details, on: :member
    get :get_plan, on: :member
  end
  resources :coop_banks
  resources :coop_branches

  resources :members do
    collection do
      post :import
    end
    get :show_coverages, on: :member
  end

  resources :coop_members do
    get :selected, on: :member
    get :member_agreements, on: :member
    get :show_insurance, on: :member
    get :find_member, on: :member
  end

  resources :denied_enrollees, only: [:index] do
    # routes for deleting all denied enrolle
    delete :destroy_all, on: :collection
  end

  resources :coop_agreements do
    resources :group_remits do

      resources :remittances, only: [:index]
    end
  end

  resources :group_remits do
    resources :remarks, controller: "group_remit/remarks"
    get "denied_members", to: "denied_members#index"
    get "download_csv", to: "denied_members#download_csv"
    delete "destroy_all", to: "denied_members#destroy_all"
    get :submit, on: :member
    get :renewal, on: :member
    resources :batches do
      get :health_dec, on: :member
      get :modal_remarks, on: :member
      collection do
        post :import
        get :approve_all
        get :all_health_decs
      end
      # get :approve_selected, on: :collection
      # get :approve_all, on: :collection
      resources :batch_health_decs, as: "health_declarations"
      resources :dependent_health_decs, as: "dep_health_declarations"
      resources :batch_dependents, as: "dependents" do
        get :health_dec, on: :member
        collection do
          get :show_all
        end
      end
      resources :batch_beneficiaries, as: "beneficiaries"
      resources :member_dependents do
        collection do
          post :create_beneficiary
          get :new_beneficiary
        end
      end
    end
  end

  resources :health_decs do
    resources :health_dec_subquestions
  end

  namespace :loan_insurance do
    resources :retentions
    resources :rates
    resources :loans
    resources :details
    resources :batches do
      get :remove_unused, on: :member
      get :terminate, on: :member
      get :modal_remarks, on: :member
      get :find_loan, on: :member
      get :adjusted, on: :member
      post :accept_adjustment, on: :member
      post :cancel_coverage, on: :member
      get :adjustments, on: :member
      collection do
        get :approve_all
      end

      member do
        get :show_unuse_batch, as: "unuse_batch"
      end

      collection do
        post :import
      end

    end

    resources :group_remits do
      get :submit, on: :member
      get :edit_or, on: :member
      get :sii_index, on: :collection
      get "lppi_summary", on: :member
    end

    resources :history, only: [:index]
  end

  # get 'loan_insurance', to: 'loan_insurance#index'
  get "insurance/accept", as: "accept_insurance"
  # get 'insurance/reject', as: 'reject_insurance'
  get "insurance/terminate", as: "terminate_insurance"

  # * Finance Module Routes
  # accounting
  namespace :accounting do
    resources :account_beginning_balances
    resources :debit_advices do
      get :new_receipt, on: :member
      post :upload_receipt, on: :member
      get :download, on: :member
    end

    resources :journals do
      get :download, on: :member
      get :for_approval_index, on: :collection
      # get :for_jv, on: :collection
      get :requests, on: :collection
    end

    resources :checks do
      # get :for_approval_index, on: :collection
      get :claimable, on: :member
      # get :cancel, on: :member
      resources :business_checks, as: 'business', except: [:index]
      get :requests, on: :collection
      resources :remarks
      get :download, on: :member
      get :print, on: :member
    end

    resources :general_disbursement_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :journal_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :receipt_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :voucher_requests, only: %i[index show]

    get "dashboard", to: "dashboard#index"
    get "for_approval", to: "dashboard#for_approval"
  end

  resources :payees

  # treasury
  namespace :treasury do
    resources :sub_accounts
    resources :payment_types
    resources :business_checks, as: 'checks', path: 'checks', only: %w[index edit update] do
      get :requests, on: :collection
      get :search, on: :collection
    end

    # resources :payments
    resources :cashier_entries do
      get :print, on: :member

app/controllers/loan_insurance/details_controller.rb
class LoanInsurance::DetailsController < ApplicationController
  before_action :set_loan_insurance_detail, only: %i[ show edit update destroy ]

  # GET /loan_insurance/details
  def index
    @loan_insurance_details = LoanInsurance::Detail.all
  end

  # GET /loan_insurance/details/1
  def show
  end

  # GET /loan_insurance/details/new
  def new
    @loan_insurance_detail = LoanInsurance::Detail.new
  end

  # GET /loan_insurance/details/1/edit
  def edit
  end

  # POST /loan_insurance/details
  def create
    @loan_insurance_detail = LoanInsurance::Detail.new(loan_insurance_detail_params)

    if @loan_insurance_detail.save
      redirect_to @loan_insurance_detail, notice: "Detail was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /loan_insurance/details/1
  def update
    if @loan_insurance_detail.update(loan_insurance_detail_params)
      redirect_to @loan_insurance_detail, notice: "Detail was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /loan_insurance/details/1
  def destroy
    @loan_insurance_detail.destroy
    redirect_to loan_insurance_details_url, notice: "Detail was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_loan_insurance_detail
    @loan_insurance_detail = LoanInsurance::Detail.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def loan_insurance_detail_params
    params.require(:loan_insurance_detail).permit(:batch_id, :unuse, :loan_amount, :premium_due, :substandard_rate, :terminate, :terinate_date, :reinsurance, :terms, :date_release, :date_mature)
  end
end

app/controllers/loan_insurance/history_controller.rb
class LoanInsurance::HistoryController < ApplicationController
  def index
    @coop_member = CoopMember.find(params[:coop_member_id])
    @loans = @coop_member.loans.decorate
    @pagy, @loans = pagy(@loans, items: 10)
    @table_headers = [
      "Date Created",
      "Type",
      "Amount",
      "Effectivity",
      "Expiry",
      "Terms",
      "Release",
      "Maturity",
      "Insurance",
      "Status"
    ]
  end
end

app/controllers/loan_insurance/loans_controller.rb
class LoanInsurance::LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # GET /loan_insurance/loans
  def index
    if current_user.userable_type == "CoopUser"
      @cooperative = current_user.userable.cooperative
      @loans = @cooperative.loans
    else
      @loans = LoanInsurance::Loan.all
    end
  end

  # GET /loan_insurance/loans/1
  def show
  end

  # GET /loan_insurance/loans/new
  def new
    if current_user.userable_type == "CoopUser"
      @cooperative = current_user.userable.cooperative
      @loan = @cooperative.loans.build
    else
      @loan = LoanInsurance::Loan.new
    end
  end

  # GET /loan_insurance/loans/1/edit
  def edit
  end

  # POST /loan_insurance/loans
  def create
    @loan = LoanInsurance::Loan.new(loan_params)

    if @loan.save
      # redirect_to @loan, notice: "Loan was successfully created."
      redirect_to loan_insurance_loans_path, notice: "Loan was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /loan_insurance/loans/1
  def update
    if @loan.update(loan_params)
      redirect_to @loan, notice: "Loan was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /loan_insurance/loans/1
  def destroy
    @loan.destroy
    redirect_to loans_url, notice: "Loan was successfully destroyed.", status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_loan
    @loan = LoanInsurance::Loan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def loan_params
    params.require(:loan_insurance_loan).permit(:name, :description, :cooperative_id, :for_sii)
  end
end

app/controllers/loan_insurance/rates_controller.rb
class LoanInsurance::RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]

  # GET /loan_insurance/rates
  def index
    @rates = LoanInsurance::Rate.all
    @grouped_rates = @rates.group_by(&:agreement)
  end

  # GET /loan_insurance/rates/1
  def show
  end

  # GET /loan_insurance/rates/new
  def new
    # @rate = LoanInsurance::Rate.new
    @agreement = Agreement.find_by(id: params[:a_id])
    @rate = @agreement.loan_rates.build
  end

  # GET /loan_insurance/rates/1/edit
  def edit
  end

  # POST /loan_insurance/rates
  def create
    # @rate = LoanInsurance::Rate.new(rate_params)
    @agreement = Agreement.find(params[:agreement])
    @rate = @agreement.loan_rates.build(rate_params)
    # raise 'errors'
    # @rate.set_rate

    if @rate.save
      @rate.set_rate
      redirect_back fallback_location: @agreement, notice: "LPPI Rate was successfully added."
      # redirect_to @rate, notice: "Rate was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /loan_insurance/rates/1
  def update
    @rate.monthly_rate = rate_params[:annual_rate].to_d / 12
    @rate.daily_rate = rate_params[:annual_rate].to_d / 365

    if @rate.update(rate_params)
      # redirect_to @rate, notice: "Rate was successfully updated."
      redirect_back fallback_location: @agreement, notice: "LPPI Rate was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /loan_insurance/rates/1
  def destroy
    @rate.destroy
    redirect_to rates_url, notice: "Rate was successfully destroyed.", status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rate
    @rate = LoanInsurance::Rate.find(params[:id])
    @agreement = Agreement.find(@rate.agreement.id)
  end

  # Only allow a list of trusted parameters through.
  def rate_params
    params.require(:loan_insurance_rate).permit(:agreement_id, :min_age, :max_age, :annual_rate, :min_amount, :max_amount, :coop_sf, :agent_sf, :nel, :nml, :contestability, :markup_rate, :markup_sf)
  end
end

app/controllers/loan_insurance/retentions_controller.rb
class LoanInsurance::RetentionsController < ApplicationController
  before_action :set_retention, only: %i[ show edit update destroy ]

  # GET /loan_insurance/retentions
  def index
    @retentions = LoanInsurance::Retention.all
  end

  # GET /loan_insurance/retentions/1
  def show
  end

  # GET /loan_insurance/retentions/new
  def new
    @retention = LoanInsurance::Retention.new
  end

  # GET /loan_insurance/retentions/1/edit
  def edit
  end

  # POST /loan_insurance/retentions
  def create
    @retention = LoanInsurance::Retention.new(retention_params)

    if @retention.save
      redirect_to @retention, notice: "Retention was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /loan_insurance/retentions/1
  def update
    if @retention.update(retention_params)
      redirect_to @retention, notice: "Retention was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /loan_insurance/retentions/1
  def destroy
    @retention.destroy
    redirect_to loan_insurance_retentions_url, notice: "Retention was successfully destroyed.", status: :see_other
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_retention
    @retention = LoanInsurance::Retention.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def retention_params
    params.require(:loan_insurance_retention).permit(:amount, :active, :date_activated, :date_deactivated)
  end
end

app/views/loan_insurance/rates/_form.html.erb
<%#= simple_form_for(@rate) do |f| %>
<%= simple_form_for(@rate, url: url, meth: meth) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-3">
    <%#= f.association :agreement %>
    <div class="row">
      <%= f.input :min_age, wrapper_html: { class: "col-md-6" }, label: "Minimum Age" %>
      <%= f.input :max_age, wrapper_html: { class: "col-md-6" }, label: "Maximum Age" %>
    </div>
    <div class="row">
    <%= f.input :min_amount, wrapper_html: { class: "col-md-6" }, label: "Minimum Amount", placeholder: "₱" %>
    <%= f.input :max_amount, wrapper_html: { class: "col-md-6" }, label: "Maximum Amount", placeholder: "₱" %>
    </div>
    <div class="row">
      <%= f.input :annual_rate, label: "Annual Rate", wrapper_html: { class: "col-md-4" } %>
      <%= f.input :coop_sf, wrapper_html: { class: "col-md-4" }, label: "Coop S.F.", placeholder: "%" %>
      <%= f.input :agent_sf, wrapper_html: { class: "col-md-4" }, label: "Agent S.F.", placeholder: "%" %>
    </div>
    <% if @rate.agreement.with_markup == true %>
      <div class="row">
        <%= f.input :markup_rate, wrapper_html: { class: "col-md-6" }, label: "Mark-up Rate", placeholder: "Monthly Rate" %>
        <%= f.input :markup_sf, wrapper_html: { class: "col-md-6" }, label: "Mark-up Rate", placeholder: "%" %>
      </div>
    <% end %>
    <div class="row">
      <%= f.input :nel, wrapper_html: { class: "col-md-4" }, label: "No Evidence Limit", placeholder: "₱" %>
      <%= f.input :nml, wrapper_html: { class: "col-md-4" }, label: "Non-medical Limit", placeholder: "₱" %>
      <%= f.input :contestability, wrapper_html: { class: "col-md-4" }, label: "Contestability", placeholder: "Months" %>
    </div>
    <%#= f.input :monthly_rate %>
    <%#= f.input :daily_rate %>

  <div class="form-actions text-end">
    <%#= link_to "Back", loan_insurance_rates_path, class: 'btn btn-secondary' %>
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/loan_insurance/rates/_old_index.html.erb
<table class ="table table-striped">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>#</th>
        <th>Coop/Plan</th>
        <th>Min Age</th>
        <th>Max Age</th>
        <th>Monthly Rate</th>
        <th>Annual Rate</th>
        <th>Daily Rate</th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @rates.each do |loan_insurance_rate| %>
        <tr>

        <th scope="row"><%= loan_insurance_rate.id %></th>
        <td>
          <% unless loan_insurance_rate.agreement.nil? %>
            <%= "#{loan_insurance_rate.agreement.cooperative.acronym} (#{loan_insurance_rate.agreement.plan.acronym})" %> 
          <% end %>
        </td>
        <td><%= loan_insurance_rate.min_age %></td>
        <td><%= loan_insurance_rate.max_age %></td>
        <td><%= loan_insurance_rate.monthly_rate %></td>
        <td><%= loan_insurance_rate.annual_rate %></td>
        <td><%= loan_insurance_rate.daily_rate %></td>
    
          <td>
            <%= link_to 'View', loan_insurance_rate, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_loan_insurance_rate_path(loan_insurance_rate), class: 'btn btn-secondary btn-sm' %>
            <%= link_to "Delete", loan_insurance_rate, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

app/views/loan_insurance/rates/_rate.html.erb
<div id="<%= dom_id rate %>">
  <p>
    <strong>Min age:</strong>
    <%= rate.min_age %>
  </p>

  <p>
    <strong>Max age:</strong>
    <%= rate.max_age %>
  </p>

  <p>
    <strong>Monthly rate:</strong>
    <%= rate.monthly_rate %>
  </p>

  <p>
    <strong>Annual rate:</strong>
    <%= rate.annual_rate %>
  </p>

  <p>
    <strong>Daily rate:</strong>
    <%= rate.daily_rate %>
  </p>

  <p>
    <strong>Min Amount:</strong>
    <%= to_currency(rate.min_amount) %>
  </p>

  <p>
    <strong>Max Amount:</strong>
    <%= to_currency(rate.max_amount) %>
  </p>

</div>

app/views/loan_insurance/rates/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/loan_insurance/rates/edit.html.erb
<!-- div class="card">
  <h5 class="card-header">Edit rate</h5>
  <div class="card-body">
    <%#= render "form", loan_insurance_rate: @loan_insurance_rate %>
  </div>
</!-->

<%= render "remote_modal", title: "Edit Rate" do %>
  <%#= render "form", loan_insurance_rate: @loan_insurance_rate %>
  <%= render "form", url: loan_insurance_rate_path(@rate), meth: 'patch' %>
<% end %>

app/views/loan_insurance/rates/index.html.erb
<%= content_tag :h1, "List of Loan Insurance Rates" %>


<div class="text-end mb-3">
  <%= link_to new_loan_insurance_rate_path, class: 'btn btn-primary' do %>
    New Rate
  <% end %>
</div>

<div class="row">
  <% @grouped_rates.each do |agreement, grs| %>
    <div class="col-xl-6 mb-3">
      <div class="card">
        <div class="card-header">
          <%= content_tag :span, agreement.cooperative.name, class: "lead" %>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <th>Age</th>
              <th>Amount</th>
              <th>Rates</th>
              <th></th>
            </thead>
            <tbody>
              <% grs.each do |rate| %>
                <tr>
                  <td><%= rate.min_age %> - <%= rate.max_age %> years old</td>
                  <td><%= to_currency(rate.min_amount) %> - <%= to_currency(rate.max_amount) %></td>
                  <td>
                    Monthly: <%= to_currency(rate.monthly_rate) %> <br>
                    Annual: <%= to_currency(rate.annual_rate) %>
                  </td>
                  <td>
                    <%= link_to "Edit", edit_loan_insurance_rate_path(rate), class: "btn btn-sm btn-success" %> | 
                    <%= link_to "Delete", rate, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>

          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/loan_insurance/rates/new.html.erb
<%= render "remote_modal", title: "New Rate" do %>
  <%#= render "form", loan_insurance_rate: @loan_insurance_rate %>
  <%= render "form", url: loan_insurance_rates_path(agreement: @agreement), meth: 'post' %>
<% end %>
<!-- <div class="card">
  <h5 class="card-header">New rate</h5>
  <div class="card-body">
  </div>
</div -->

app/views/loan_insurance/rates/show.html.erb
<%= render @rate %>

<div>
  <%= link_to "Edit", edit_loan_insurance_rate_path(@rate), class: 'btn btn-primary' %> |
  <%= link_to "Back", loan_insurance_rates_path, class: 'btn btn-primary' %>

  <%= button_to "Delete", @loan_insurance_rate, method: :delete, class: 'btn btn-danger' %>
</div>