config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :banks
  resources :branches
  resources :employee_teams
  resources :teams do
    get :selected, on: :member
  end

  resources :demo_schedules
  resources :transmittals do
    get :remove_or, on: :member
  end

  resources :special_arrangements
  resources :sip_pbs
  resources :sip_abs
  resources :koopamilya_pbs
  resources :koopamilya_abs
  resources :reinsurance_members
  resources :reinsurer_ri_batches
  resources :reinsurers
  resources :claim_request_for_payments
  resources :claim_payments
  get "actuarial/index"

  namespace :actuarial do
    resources :reserves
    resources :reserve_batches
  end

  resources :group_proposals
  resources :unit_benefits
  resources :plan_units do
    get :find_units, on: :member
  end
  resources :reinsurances do
    get :reserves_index, on: :collection
  end
  namespace :claims do
    resources :claim_types, :claim_documents, :claim_type_benefits, :claim_confinements, :claim_benefits, :claim_coverages, :claim_distributions, :claim_type_natures, :claim_type_agreements, :claim_retrievals

    resources :cf_accounts do
      get :index_critical, to: "cf_accounts#index_critical", on: :collection
    end

    resources :cf_replenishes do
      get :update_status, to: "cf_replenishes#update_status", on: :member
    end
    resources :cf_availments do
      get :update_status, to: "cf_availments#update_status", on: :member
    end
    resources :claim_coverage_reinsurances do
      get :claim_reinsurance_create, to: "claim_coverage_reinsurances#claim_reinsurance_create", as: "claim_ri_create", on: :collection
      get :claim_reinsurance_update, to: "claim_coverage_reinsurances#claim_reinsurance_update", as: "claim_ri_update", on: :member
    end

    resources :causes do
      post 'create_cause', to: "causes#create"
    end
    resources :claim_attachments do
      get :attach_new_doc, on: :collection
    end

    resources :claim_type_documents do
      get :document_request, to: "claim_type_documents#document_request", on: :member
    end

    resources :process_claims do
      get :new_coop, to: "process_claims#new_coop", on: :collection
      post :create_coop, to: "process_claims#create_coop", on: :collection
      get :index_coop, to: "process_claims#index_coop", on: :collection
      get :index_show, on: :collection
      get :index_claim_type, on: :collection
      get :show_coop, on: :member
      get :claim_route, on: :member
      get :claims_file, on: :member
      get :claim_process, on: :member
      get :update_status, on: :member
      get :new_ca, to: "process_claims#new_ca", on: :collection
      get :edit_ca, to: "process_claims#edit_ca", on: :member
      get :edit_coop, to: "process_claims#edit_coop", on: :member
      post :create_ca, to: "process_claims#create_ca", on: :collection
      patch :update_ca, to: "process_claims#update_ca", on: :member
      patch :update_coop, to: "process_claims#update_coop", on: :member
      get :print_sheet, to: "process_claims#print_sheet", on: :member
      get :claims_dashboard, to: "process_claims#claims_dashboard", on: :collection
      get :approve_claim_debit, on: :member
      # get :claimable, on: :collection
      resources :remarks
    end

    resources :claim_remarks do
      get :new_status, to: "claim_remarks#new_status", on: :collection
      post :create_status, to: "claim_remarks#create_status", on: :collection
      get :message_history, to: "claim_remarks#message_history", on: :collection
      get :read_message, on: :member
      get :unread_messages, on: :collection
    end
  end




  resources :documents
  resources :emp_approvers
  get "med_directors/home"
  get "med_director/index"

  resources :emp_agreements do
    get :transfer_index, on: :collection
    get :update_ea_selected, on: :collection
    patch :transfer_agreements, on: :collection
    get :inactive_sub, on: :member
  end
  # resources :denied_dependents

  resources :anniversaries, :agent_groups, :departments, :agents, :coop_users, :employees, :product_benefits

  resources :plans do
    get :selected, on: :member
    get :show_rates, on: :member
    get :show_fields, on: :member
  end

  resources :dashboards do
    get :actuarial, on: :collection
    get :claims, on: :collection
    get :mis, on: :collection
    get :coop, on: :collection
    get :treasury, on: :collection
    get :accounting, on: :collection
    get :admin, on: :collection
  end
  
  resources :analytics do 
    get :claims, on: :collection
  end

  resources :user do
    get :approved, on: :member
    get :admin_dashboard, on: :collection
  end

  resources :agreement_benefits do
    get :selected, on: :member
  end

  resources :agreements do
    get :show_details, on: :member
    post :update_ors, on: :member
    get :selected, on: :member
  end

  # resources :agreement_benefits
  # resources :plans
  # resources :agreements
  # resources :cooperatives
  resources :coop_types
  resources :geo_barangays

  resources :geo_municipalities do
    get :selected, on: :member
  end

  resources :geo_provinces do
    get :selected, on: :member
  end

  resources :geo_regions do
    get :selected, on: :member
  end
  # resources :agent_groups
  # resources :departments
  # resources :agents
  # resources :coop_users
  # resources :employees
  resources :benefits
  get 'pages/home'
  get 'pages/coso'
  get 'pages/president'
  get 'pages/coop'
  get 'pages/find_graph'
  get "update_charts", to: "pages#update_charts", as: "update_charts"
  get "select_charts", to: "pages#select_charts", as: "select_charts"
  get "update_prem_annum", to: "pages#update_prem_annum", as: "update_prem_annum"
  # get "/pages/modals/modal_charts", to: "pages#modal_charts", as: "modal_charts"
  get "modal_charts", to: "pages#modal_charts", as: "modal_charts"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/progress", to: "progress#show"
  get "/progress/update", to: "progress#update"

  # * Coop Module
  namespace :coop do
    get "dashboard", to: "dashboard#index"
  end

  resources :cooperatives do
    get :selected, on: :member
    get :select_agreement, on: :member
    get :details, on: :member
    get :get_plan, on: :member
  end
  resources :coop_banks
  resources :coop_branches

  resources :members do
    collection do
      post :import
    end
    get :show_coverages, on: :member
  end

  resources :coop_members do
    get :selected, on: :member
    get :member_agreements, on: :member
    get :show_insurance, on: :member
    get :find_member, on: :member
  end

  resources :denied_enrollees, only: [:index] do
    # routes for deleting all denied enrolle
    delete :destroy_all, on: :collection
  end

  resources :coop_agreements do
    resources :group_remits do

      resources :remittances, only: [:index]
    end
  end

  resources :group_remits do
    resources :remarks, controller: "group_remit/remarks"
    get "denied_members", to: "denied_members#index"
    get "download_csv", to: "denied_members#download_csv"
    delete "destroy_all", to: "denied_members#destroy_all"
    get :submit, on: :member
    get :renewal, on: :member
    resources :batches do
      get :health_dec, on: :member
      get :modal_remarks, on: :member
      collection do
        post :import
        get :approve_all
        get :all_health_decs
      end
      # get :approve_selected, on: :collection
      # get :approve_all, on: :collection
      resources :batch_health_decs, as: "health_declarations"
      resources :dependent_health_decs, as: "dep_health_declarations"
      resources :batch_dependents, as: "dependents" do
        get :health_dec, on: :member
        collection do
          get :show_all
        end
      end
      resources :batch_beneficiaries, as: "beneficiaries"
      resources :member_dependents do
        collection do
          post :create_beneficiary
          get :new_beneficiary
        end
      end
    end
  end

  resources :health_decs do
    resources :health_dec_subquestions
  end

  namespace :loan_insurance do
    resources :retentions
    resources :rates
    resources :loans
    resources :details
    resources :batches do
      get :remove_unused, on: :member
      get :terminate, on: :member
      get :modal_remarks, on: :member
      get :find_loan, on: :member
      get :adjusted, on: :member
      post :accept_adjustment, on: :member
      post :cancel_coverage, on: :member
      get :adjustments, on: :member
      collection do
        get :approve_all
      end

      member do
        get :show_unuse_batch, as: "unuse_batch"
      end

      collection do
        post :import
      end

    end

    resources :group_remits do
      get :submit, on: :member
      get :edit_or, on: :member
      get :sii_index, on: :collection
      get "lppi_summary", on: :member
    end

    resources :history, only: [:index]
  end

  # get 'loan_insurance', to: 'loan_insurance#index'
  get "insurance/accept", as: "accept_insurance"
  # get 'insurance/reject', as: 'reject_insurance'
  get "insurance/terminate", as: "terminate_insurance"

  # * Finance Module Routes
  # accounting
  namespace :accounting do
    resources :account_beginning_balances
    resources :debit_advices do
      get :new_receipt, on: :member
      post :upload_receipt, on: :member
      get :download, on: :member
    end

    resources :journals do
      get :download, on: :member
      get :for_approval_index, on: :collection
      # get :for_jv, on: :collection
      get :requests, on: :collection
    end

    resources :checks do
      # get :for_approval_index, on: :collection
      get :claimable, on: :member
      # get :cancel, on: :member
      resources :business_checks, as: 'business', except: [:index]
      get :requests, on: :collection
      resources :remarks
      get :download, on: :member
      get :print, on: :member
    end

app/controllers/accounting/dashboard_controller.rb
class Accounting::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    for_approvals
    request = Accounting::VoucherRequest.where(status: :pending)
    @check_req =request.where(payment_type: :check_voucher).order(created_at: :desc)
    @da_req =request.where(payment_type: :debit_advice).order(created_at: :desc)
    @journal_req =request.where(payment_type: :journal_voucher).order(created_at: :desc)
  end

  def for_approval
    for_approvals
  end

  private

  def for_approvals
    check_for_approval = Accounting::Check.where(status: :for_approval)
    da_for_approval = Accounting::DebitAdvice.where(status: :for_approval)
    journal_for_approval = Accounting::Journal.where(status: :for_approval)
    @for_approvals = (check_for_approval + da_for_approval + journal_for_approval).sort_by(&:created_at)
  end
end

app/controllers/audit/dashboard_controller.rb
class Audit::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/coop/dashboard_controller.rb
class Coop::DashboardController < ApplicationController
  def index
    @cooperative = current_user.userable.cooperative
    @notifications = @cooperative.notifications

    @coop_group_remits = @cooperative.group_remits
    @pending_lppi = LoanInsurance::Batch.get_pending_lppi(@coop_group_remits)
    
    #for graphs
    @age_bracket = [
      ["18-65", @cooperative.get_age_demo("regular")],
      ["66-70", @cooperative.get_age_demo("66")],
      ["71-75", @cooperative.get_age_demo("71")],
      ["76-80", @cooperative.get_age_demo("76")],
      ["81-85", @cooperative.get_age_demo("81")]
    ]

    @gender_counts = [
      ["Male", @cooperative.coop_members.includes(:member).where(member: { gender: ['Male', "MALE", "M"] }).count],
      ["Female", @cooperative.coop_members.includes(:member).where(member: { gender: ['Female', "FEMALE", "F"] }).count],
      ["Other", @cooperative.coop_members.includes(:member).where(member: { gender: ['-', nil] }).count]
    ]
  end
end

app/controllers/mis/cooperatives_controller.rb
class Mis::CooperativesController < ApplicationController
  def index
    @cooperatives = Cooperative.all
  end
end

app/controllers/mis/dashboard_controller.rb
class Mis::DashboardController < ApplicationController
  def index
    @encoded = GroupRemit.where(mis_entry: true)
    # @not_encoded = Treasury::CashierEntry.all
    @not_encoded = Treasury::CashierEntry.posted.includes(:agreement).where.not(or_no: GroupRemit.pluck(:official_receipt))
    @transmitted = TransmittalOr.joins(:transmittal).where(transmittal: { transmittal_type: :mis })
    # @with_ors = GroupRemit.where.not(official_receipt: nil).where(mis_entry: true)
    @with_ors = GroupRemit.where.not(id: TransmittalOr.with_ors_already).where(mis_entry: true)

    @lppi_encoded = LoanInsurance::Batch.get_lppi_batches_count(current_user.id)
    @gyrt_encoded = Batch.get_gyrt_encoded(current_user.id)
  end

  def view_ors
    # raise 'error'
    @type = params[:t]
    # @encoded = GroupRemit.where(mis_entry: true)
    # @transmitted = TransmittalOr.joins(:transmittal).where(transmittal: { transmittal_type: :mis })
    # @with_ors = GroupRemit.where.not(official_receipt: nil).where(mis_entry: true)

    @ors = case @type
    when "enc"
      GroupRemit.where(mis_entry: true).order(created_at: :desc)
    when "nt"
      # GroupRemit.where.not(official_receipt: nil).where(mis_entry: true)
      GroupRemit.where.not(id: TransmittalOr.with_ors_already).where(mis_entry: true)
    when "ne"
      # Treasury::CashierEntry.all
      Treasury::CashierEntry.posted.includes(:agreement).where.not(or_no: GroupRemit.pluck(:official_receipt))
    end

    if params[:search].present?
      if @type == "ne"
        @filtered_ors = @ors.where(or_no: params[:search])
      else
        @filtered_ors = @ors.where(official_receipt: params[:search])
      end
    else
      @filtered_ors = @ors
    end

    if params[:e].present?
      @filtered_ors = @filtered_ors.where(mis_user: params[:e])
    end

    @pagy_ors, @filtered_ors = pagy(@filtered_ors, items: 25)
  end
end

app/controllers/mis/members_controller.rb
class Mis::MembersController < ApplicationController
  def index
    if can? :read, Member
      @q = Member.ransack(params[:q])
      @members = @q.result.order(:last_name, :first_name)
      @pagy, @members = pagy(@members, items: 10)
    else
      head :forbidden
    end
  end

  def show
    if can? :read, Member
      @member = Member.find(params[:id])
      @memberships = @member.coop_members.includes(:agreements)
    else
      head :forbidden
    end
  end


end

app/controllers/treasury/dashboard_controller.rb
class Treasury::DashboardController < ApplicationController
  def index
    @for_approvals = Treasury::CashierEntry.where(status: :for_approval)
    @for_ors = Payment.where(status: :for_review)
    @vouchers = Accounting::Check.where(status: :posted, claimable: false, audit: :approved)
    @debit_advices = Accounting::DebitAdvice.approved.pending_payout
  end

  def for_approval
    @for_approvals = Treasury::CashierEntry.where(status: :for_approval).order(created_at: :desc)
  end
end

app/views/mis/dashboard/index.html.erb
<h1>MIS Dashboard</h1>

<div class="row">


  <div class="col-6">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="lead fw-bold">Monitoring</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <th>ORS</th>
              <th>Count</th>
              <th></th>
            </thead>
            <tbody>
              <tr>
                <td>Encoded</td>
                <td><%= @encoded.count %></td>
                <td><%= link_to "View", mis_view_ors_path(t: "enc"), class: "btn btn-sm btn-outline-primary" %></td>
              </tr>
              <tr>
                <td>Not Encoded</td>
                <td><%= @not_encoded.count %></td>
                <td><%= link_to "View", mis_view_ors_path(t: "ne"), class: "btn btn-sm btn-outline-primary" %></td>
              </tr>
              <tr>
                <td>Transmitted</td>
                <td><%= @transmitted.count %></td>
                <td><%= link_to "View", transmittals_path, class: "btn btn-sm btn-outline-primary" %></td>
              </tr>
              <tr>
                <td>Not Transmitted</td>
                <td><%= @with_ors.count %></td>
                <td><%= link_to "View", mis_view_ors_path(t: "nt"), class: "btn btn-sm btn-outline-primary" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="lead fw-bold">User Progress</h5>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <th>Plan</th>
              <th>Total Encoded</th>
            </thead>
            <tbody>
              <tr>
                <td>LPPI</td>
                <td><%= number_with_delimiter(@lppi_encoded) %></td>
              </tr>
              <tr>
                <td>GYRT</td>
                <td><%= number_with_delimiter(@gyrt_encoded) %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="lead fw-bold">Graphs (Daily Encoding)</h5>
        </div>
        <div class="card-body">
          <p class="lead fst-italic">Coming soon.</p>
        </div>
      </div>
    </div>

    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="lead fw-bold">Graphs (Monthly Encoding)</h5>
        </div>
        <div class="card-body">
          <p class="lead fst-italic">Coming soon.</p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/mis/dashboard/view_ors.html.erb
<div class="<%= flex_justify_align('between', 'center') %>">
  <div class="<%= flex_justify_align('', 'center') %> gap-2">
    <%= link_to :back , class: "btn btn-sm btn-outline-secondary" do %>
      <%= bootstrap_icon "chevron-left" %>
    <% end %>
    <h1 class="mb-0"><%= view_ors_title(@type, params[:e]) %></h1>

    <%= form_with url: mis_view_ors_path, method: :get do %>
      <div class="form-group d-flex justify-content-end gap-1">
        <%= text_field_tag 'search', 
          nil, 
          placeholder: 'O.R. Number', 
          class: "form-control", 
          style: "width: auto"
        %>
        <%= hidden_field_tag :t, @type %>
        <%= button_tag(type: 'submit', class: small_btn('warning'), style: "width: 40px") do %>
          <i class='bi bi-search'></i>
        <% end %>
        <%= link_to mis_view_ors_path(t: @type), class: "btn btn-secondary", title: "Reload" do %>
          <i class="bi bi-arrow-clockwise"></i>
        <% end %>
      </div>
    <% end %>

  </div>

  <div class="">
    <%== pagy_bootstrap_nav(@pagy_ors) if @pagy_ors.pages > 1 %>
  </div>
</div>

<% unless @type == "ne" %>
  <%= form_tag new_transmittal_path(b_ids: []), method: :get, data: { turbo_frame: "modal" } do %>
    <% if @type == "nt" %>
      <div class="float-end">
        <%= submit_tag 'Transmit selected', name: 'transmit', onclick: "return confirm('Are you sure?')", class: "btn btn-primary mb-2" %>
      </div>
    <% end %>
    <table class="<%= table_sm_hoverable %> mt-3" data-controller="retain-checkbox">
      <thead>
        <% if @type == "nt" %>
          <th></th>
        <% end %>
        <th class="text-center">OR #</th>
        <th class="text-center">OR Date</th>
        <th class="text-center">Cooperative</th>
        <th class="text-center">Total</th>
        <th class="text-center">Plan</th>
        <th class="text-center">Remarks</th>
      </thead>
      <tbody>
        <% if @filtered_ors.count <= 0 %>
          <tr>
            <% if @type == "nt" %>
              <td colspan=8 class="lead text-center">NO RECORD(S).</td>
            <% else %>
              <td colspan=7 class="lead text-center">NO RECORD(S).</td>
            <% end %>
          </tr>
        <% else %>
          <% @filtered_ors.order(created_at: :desc).each do |group_remit| %>
            <tr class="text-center">
              <% if @type == "nt" %>
                <td><%= check_box_tag "b_ids[]", group_remit.id, false, id: "b_ids[#{group_remit.id}]", data: { checkbox_select_all_target: "child", action: "change->checkbox-select-all#toggleParent" } %></td>
              <% end %>
              <td class="text-center"><%= group_remit.official_receipt %></td>
              <td class="text-center"><%= group_remit.get_or_date %></td>
              <td class="text-center"><%= group_remit.agreement.cooperative %></td>
              <td class="text-center"><%= group_remit.count_batches %></td>
              <td class="text-center"><%= group_remit.agreement.plan.acronym %></td>
              <td class="text-center"></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>

<% else %>
  <table class="<%= table_sm_hoverable %> mt-3">
    <thead>
      <th class="text-center">OR No.</th>
      <th class="text-center" style="min-width: 100px">OR Date</th>
      <th class="text-center">Cooperative</th>
      <th class="text-center">Plan</th>
      <th></th>
    </thead>
    <tbody>
      
      <% if @filtered_ors.count <= 0 %>
        <tr>
          <td colspan=6 class="lead text-center">NO RECORD(S).</td>
        </tr>
      <% else %>
        <% @filtered_ors.order(created_at: :desc).each do |payment| %>
          <tr>
            <td class="<%= centered_cell %>" ><%= payment.or_no %></td>
            <td class="<%= centered_cell %>" ><%= payment.or_date %></td>
            <td class="<%= centered_cell %>">
              <%= payment.entriable %> <br>
              <%= coop_with_moa(payment.agreement.present?) %>
            </td>
            <td class="<%= centered_cell %>"><%= payment&.plan %></td>
            <td class="<%= centered_cell %>">
              <% unless payment&.check_if_mis_encoded.nil? %>
                <p>O.R. already encoded.</p>
              <% else %>

                <% if payment&.agreement&.plan&.acronym == "LPPI" %>
                  <%= link_to "Encode", loan_insurance_group_remits_path(or_no: payment.or_no, agreement_id: payment.agreement.id, c_id: payment.entriable.id), data: { turbo_method: :post }, class: "btn btn-sm btn-outline-primary", onclick: "return confirm('Are you sure?')" %>
                <% elsif ["GYRT", "GYRTFR", "GYRTBR"].include?(payment&.agreement&.plan&.acronym) %>
                  <% if payment.agreement.anniversary_type.nil? or payment.agreement.anniversary_type.downcase == '12 months' %>
                    <% current_batch_remit = payment.agreement.group_remits.find_by(type: 'BatchRemit', effectivity_date: Date.today.beginning_of_month) %>
          
                    <% unless current_batch_remit.present? %>
                      <%= button_to "New Batch", group_remits_path, 
                        method: :post, 
                        params: { 
                          agreement_id: payment.agreement.id, 
                          anniversary_id: nil,
                          anniv_type: 'none',
                          type: 'BatchRemit',
                          or_no: payment.or_no,
                          c_id: payment.entriable.id
                        }, 
                        class: small_btn('outline-primary'), 
                        data: { turbo: false }, onclick: "return confirm('Are you sure?')" 
                      %>
                    <% else %>
                      <%= button_to "Encode", group_remits_path, 
                        method: :post, 
                        params: { 
                          agreement_id: payment.agreement.id, 
                          anniversary_id: payment.agreement.anniversaries[0]&.id, 
                          anniv_type: payment.agreement.anniversary_type,
                          type: 'Remittance',
                          batch_remit_id: current_batch_remit.id,
                          or_no: payment.or_no,
                          c_id: payment.entriable.id
                        }, 
                        class: small_btn('outline-primary'), 
                        data: { turbo: false }, onclick: "return confirm('Are you sure?')" 
                      %>
                    <% end %>

                  <% elsif payment.agreement.anniversary_type.downcase == 'single' %>
                    <% current_batch_remit = payment.agreement.group_remits.find_by(type: 'BatchRemit')%>

                    <% unless current_batch_remit.present? %>
                      <%= button_to "Encode", group_remits_path, 
                        method: :post, 
                        params: { 
                          agreement_id: payment.agreement.id, 
                          anniversary_id: payment.agreement.anniversaries[0].id,
                          anniv_type: 'single',
                          type: 'BatchRemit',
                          or_no: payment.or_no,
                          c_id: payment.entriable.id
                        }, 
                        class: small_btn('outline-primary'), 
                        data: { turbo: false } , onclick: "return confirm('Are you sure?')" 
                      %>
                    <% else %>
                      <%= button_to "Encode", group_remits_path, 
                        method: :post, 
                        params: { 
                          agreement_id: payment.agreement.id, 
                          anniversary_id: payment.agreement.anniversaries[0].id, 
                          anniv_type: payment.agreement.anniversary_type,
                          type: 'Remittance',
                          batch_remit_id: current_batch_remit.id,
                          or_no: payment.or_no,
                          c_id: payment.entriable.id
                        }, 
                        class: small_btn('success'), 
                        data: { turbo: false } , onclick: "return confirm('Are you sure?')" 
                      %>
                    <% end %>
                  <% end %>
                <% end %>

              <% end %>
              <%#= link_to "Encode", payment&.agreement, class: "btn btn-sm btn-primary" %>
            </td>
          </tr>
        <% end %>

      <% end %>
    </tbody>
  </table>
<% end %>