config/routes.rb
    resources :claim_types, :claim_documents, :claim_type_benefits, :claim_confinements, :claim_benefits, :claim_coverages, :claim_distributions, :claim_type_natures, :claim_type_agreements, :claim_retrievals

    resources :cf_accounts do
      get :index_critical, to: "cf_accounts#index_critical", on: :collection
    end

    resources :cf_replenishes do
      get :update_status, to: "cf_replenishes#update_status", on: :member
    end
    resources :cf_availments do
      get :update_status, to: "cf_availments#update_status", on: :member
    end
    resources :claim_coverage_reinsurances do
      get :claim_reinsurance_create, to: "claim_coverage_reinsurances#claim_reinsurance_create", as: "claim_ri_create", on: :collection
      get :claim_reinsurance_update, to: "claim_coverage_reinsurances#claim_reinsurance_update", as: "claim_ri_update", on: :member
    end

    resources :causes do
      post 'create_cause', to: "causes#create"
    end
    resources :claim_attachments do
      get :attach_new_doc, on: :collection
    end

    resources :claim_type_documents do
      get :document_request, to: "claim_type_documents#document_request", on: :member
    end

    resources :process_claims do
      get :new_coop, to: "process_claims#new_coop", on: :collection
      post :create_coop, to: "process_claims#create_coop", on: :collection
      get :index_coop, to: "process_claims#index_coop", on: :collection
      get :index_show, on: :collection
      get :index_claim_type, on: :collection
      get :show_coop, on: :member
      get :claim_route, on: :member
      get :claims_file, on: :member
      get :claim_process, on: :member
      get :update_status, on: :member
      get :new_ca, to: "process_claims#new_ca", on: :collection
      get :edit_ca, to: "process_claims#edit_ca", on: :member
      get :edit_coop, to: "process_claims#edit_coop", on: :member
      post :create_ca, to: "process_claims#create_ca", on: :collection
      patch :update_ca, to: "process_claims#update_ca", on: :member
      patch :update_coop, to: "process_claims#update_coop", on: :member
      get :print_sheet, to: "process_claims#print_sheet", on: :member
      get :claims_dashboard, to: "process_claims#claims_dashboard", on: :collection
      get :approve_claim_debit, on: :member
      # get :claimable, on: :collection
      resources :remarks
    end

    resources :claim_remarks do
      get :new_status, to: "claim_remarks#new_status", on: :collection
      post :create_status, to: "claim_remarks#create_status", on: :collection
      get :message_history, to: "claim_remarks#message_history", on: :collection
      get :read_message, on: :member
      get :unread_messages, on: :collection
    end
  end




  resources :documents
  resources :emp_approvers
  get "med_directors/home"
  get "med_director/index"

  resources :emp_agreements do
    get :transfer_index, on: :collection
    get :update_ea_selected, on: :collection
    patch :transfer_agreements, on: :collection
    get :inactive_sub, on: :member
  end
  # resources :denied_dependents

  resources :anniversaries, :agent_groups, :departments, :agents, :coop_users, :employees, :product_benefits

  resources :plans do
    get :selected, on: :member
    get :show_rates, on: :member
    get :show_fields, on: :member
  end

  resources :dashboards do
    get :actuarial, on: :collection
    get :claims, on: :collection
    get :mis, on: :collection
    get :coop, on: :collection
    get :treasury, on: :collection
    get :accounting, on: :collection
    get :admin, on: :collection
  end
  
  resources :analytics do 
    get :claims, on: :collection
  end

  resources :user do
    get :approved, on: :member
    get :admin_dashboard, on: :collection
  end

  resources :agreement_benefits do
    get :selected, on: :member
  end

  resources :agreements do
    get :show_details, on: :member
    post :update_ors, on: :member
    get :selected, on: :member
  end

  # resources :agreement_benefits
  # resources :plans
  # resources :agreements
  # resources :cooperatives
  resources :coop_types
  resources :geo_barangays

  resources :geo_municipalities do
    get :selected, on: :member
  end

  resources :geo_provinces do
    get :selected, on: :member
  end

  resources :geo_regions do
    get :selected, on: :member
  end
  # resources :agent_groups
  # resources :departments
  # resources :agents
  # resources :coop_users
  # resources :employees
  resources :benefits
  get 'pages/home'
  get 'pages/coso'
  get 'pages/president'
  get 'pages/coop'
  get 'pages/find_graph'
  get "update_charts", to: "pages#update_charts", as: "update_charts"
  get "select_charts", to: "pages#select_charts", as: "select_charts"
  get "update_prem_annum", to: "pages#update_prem_annum", as: "update_prem_annum"
  # get "/pages/modals/modal_charts", to: "pages#modal_charts", as: "modal_charts"
  get "modal_charts", to: "pages#modal_charts", as: "modal_charts"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/progress", to: "progress#show"
  get "/progress/update", to: "progress#update"

  # * Coop Module
  namespace :coop do
    get "dashboard", to: "dashboard#index"
  end

  resources :cooperatives do
    get :selected, on: :member
    get :select_agreement, on: :member
    get :details, on: :member
    get :get_plan, on: :member
  end
  resources :coop_banks
  resources :coop_branches

  resources :members do
    collection do
      post :import
    end
    get :show_coverages, on: :member
  end

  resources :coop_members do
    get :selected, on: :member
    get :member_agreements, on: :member
    get :show_insurance, on: :member
    get :find_member, on: :member
  end

  resources :denied_enrollees, only: [:index] do
    # routes for deleting all denied enrolle
    delete :destroy_all, on: :collection
  end

  resources :coop_agreements do
    resources :group_remits do

      resources :remittances, only: [:index]
    end
  end

  resources :group_remits do
    resources :remarks, controller: "group_remit/remarks"
    get "denied_members", to: "denied_members#index"
    get "download_csv", to: "denied_members#download_csv"
    delete "destroy_all", to: "denied_members#destroy_all"
    get :submit, on: :member
    get :renewal, on: :member
    resources :batches do
      get :health_dec, on: :member
      get :modal_remarks, on: :member
      collection do
        post :import
        get :approve_all
        get :all_health_decs
      end
      # get :approve_selected, on: :collection
      # get :approve_all, on: :collection
      resources :batch_health_decs, as: "health_declarations"
      resources :dependent_health_decs, as: "dep_health_declarations"
      resources :batch_dependents, as: "dependents" do
        get :health_dec, on: :member
        collection do
          get :show_all
        end
      end
      resources :batch_beneficiaries, as: "beneficiaries"
      resources :member_dependents do
        collection do
          post :create_beneficiary
          get :new_beneficiary
        end
      end
    end
  end

  resources :health_decs do
    resources :health_dec_subquestions
  end

  namespace :loan_insurance do
    resources :retentions
    resources :rates
    resources :loans
    resources :details
    resources :batches do
      get :remove_unused, on: :member
      get :terminate, on: :member
      get :modal_remarks, on: :member
      get :find_loan, on: :member
      get :adjusted, on: :member
      post :accept_adjustment, on: :member
      post :cancel_coverage, on: :member
      get :adjustments, on: :member
      collection do
        get :approve_all
      end

      member do
        get :show_unuse_batch, as: "unuse_batch"
      end

      collection do
        post :import
      end

    end

    resources :group_remits do
      get :submit, on: :member
      get :edit_or, on: :member
      get :sii_index, on: :collection
      get "lppi_summary", on: :member
    end

    resources :history, only: [:index]
  end

  # get 'loan_insurance', to: 'loan_insurance#index'
  get "insurance/accept", as: "accept_insurance"
  # get 'insurance/reject', as: 'reject_insurance'
  get "insurance/terminate", as: "terminate_insurance"

  # * Finance Module Routes
  # accounting
  namespace :accounting do
    resources :account_beginning_balances
    resources :debit_advices do
      get :new_receipt, on: :member
      post :upload_receipt, on: :member
      get :download, on: :member
    end

    resources :journals do
      get :download, on: :member
      get :for_approval_index, on: :collection
      # get :for_jv, on: :collection
      get :requests, on: :collection
    end

    resources :checks do
      # get :for_approval_index, on: :collection
      get :claimable, on: :member
      # get :cancel, on: :member
      resources :business_checks, as: 'business', except: [:index]
      get :requests, on: :collection
      resources :remarks
      get :download, on: :member
      get :print, on: :member
    end

    resources :general_disbursement_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :journal_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :receipt_book, only: %i[index] do
      get :pdf, on: :collection
    end

    resources :voucher_requests, only: %i[index show]

    get "dashboard", to: "dashboard#index"
    get "for_approval", to: "dashboard#for_approval"
  end

  resources :payees

  # treasury
  namespace :treasury do
    resources :sub_accounts
    resources :payment_types
    resources :business_checks, as: 'checks', path: 'checks', only: %w[index edit update] do
      get :requests, on: :collection
      get :search, on: :collection
    end

    # resources :payments
    resources :cashier_entries do
      get :print, on: :member
      get :download, on: :member
      get :cancel, on: :member
      get :for_approval_index, on: :collection

app/models/accounting.rb
module Accounting
  def self.table_name_prefix
    "accounting_"
  end
end

app/controllers/accounting/account_beginning_balances_controller.rb
class Accounting::AccountBeginningBalancesController < ApplicationController
  before_action :set_accounting_account_beginning_balance, only: %i[ show edit update destroy ]

  # GET /accounting/account_beginning_balances
  def index
    @accounting_account_beginning_balances = Accounting::AccountBeginningBalance.all
  end

  # GET /accounting/account_beginning_balances/1
  def show
  end

  # GET /accounting/account_beginning_balances/new
  def new
    @accounting_account_beginning_balance = Accounting::AccountBeginningBalance.new
  end

  # GET /accounting/account_beginning_balances/1/edit
  def edit
  end

  # POST /accounting/account_beginning_balances
  def create
    @accounting_account_beginning_balance = Accounting::AccountBeginningBalance.new(accounting_account_beginning_balance_params)

    if @accounting_account_beginning_balance.save
      redirect_to @accounting_account_beginning_balance, notice: "Account beginning balance was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounting/account_beginning_balances/1
  def update
    if @accounting_account_beginning_balance.update(accounting_account_beginning_balance_params)
      redirect_to @accounting_account_beginning_balance, notice: "Account beginning balance was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /accounting/account_beginning_balances/1
  def destroy
    @accounting_account_beginning_balance.destroy
    redirect_to accounting_account_beginning_balances_url, notice: "Account beginning balance was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_account_beginning_balance
      @accounting_account_beginning_balance = Accounting::AccountBeginningBalance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accounting_account_beginning_balance_params
      params.require(:accounting_account_beginning_balance).permit(:account_id, :balance, :year)
    end
end

app/controllers/accounting/business_checks_controller.rb
class Accounting::BusinessChecksController < ApplicationController
  before_action :set_check, only: %i[ show edit update destroy ]
  before_action :set_voucher_and_checks, only: %i[ new create edit update destroy]

  def show
  end

  def new
    last_check_no = @business_checks.maximum(:check_number)
    initiate_check_no = last_check_no ? last_check_no + 1 : 1
    @check = @business_checks.build(amount: @voucher.amount, check_date: Date.today, check_number: initiate_check_no, check_type: :regular)
  end

  def edit
  end

  def create
    @check = @business_checks.build(check_params)
    @total_amount = @business_checks.sum(:amount) + @check.amount

    if @total_amount > @voucher.amount
      return redirect_to accounting_check_path(@voucher), alert: "Business check denied. Total amount of business checks is greater than the voucher amount."
    end

    if @check.save
      redirect_to accounting_check_path(@voucher), notice: "Business check added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @check.update(check_params)
      redirect_to accounting_check_path(@voucher), notice: "Business check updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @check.destroy
      redirect_to accounting_check_path(@voucher), alert: "Business check deleted.", status: :see_other
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_check
    @check = Treasury::BusinessCheck.find(params[:id])
  end

  def set_voucher_and_checks
    @voucher = Accounting::Check.find(params[:check_id])
    @business_checks = @voucher.business_checks
  end

  # Only allow a list of trusted parameters through.
  def check_params
    params.require(:treasury_business_check).permit(:check_number, :check_date, :amount, :check_type, :payee)
  end
end

app/controllers/accounting/dashboard_controller.rb
class Accounting::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    for_approvals
    request = Accounting::VoucherRequest.where(status: :pending)
    @check_req =request.where(payment_type: :check_voucher).order(created_at: :desc)
    @da_req =request.where(payment_type: :debit_advice).order(created_at: :desc)
    @journal_req =request.where(payment_type: :journal_voucher).order(created_at: :desc)
  end

  def for_approval
    for_approvals
  end

  private

  def for_approvals
    check_for_approval = Accounting::Check.where(status: :for_approval)
    da_for_approval = Accounting::DebitAdvice.where(status: :for_approval)
    journal_for_approval = Accounting::Journal.where(status: :for_approval)
    @for_approvals = (check_for_approval + da_for_approval + journal_for_approval).sort_by(&:created_at)
  end
end

app/controllers/accounting/general_disbursement_book_controller.rb
class Accounting::GeneralDisbursementBookController < ApplicationController
  def index
  end

  def pdf
    if params[:date_from].present? && params[:date_to].present?
      check_vouchers = Accounting::Check.where(post_date: params[:date_from].to_date..params[:date_to].to_date, status: :posted)

      if check_vouchers.present?
        Accounting::Check.disbursement_book_pdf(current_user.userable.id, params[:date_from], params[:date_to], "general_disbursement_book")

        redirect_to accounting_general_disbursement_book_index_path, notice: "Report is being generated. Please wait for a moment."
      else
        redirect_to accounting_general_disbursement_book_index_path, alert: "No check vouchers found"
      end
    else
      redirect_to accounting_general_disbursement_book_index_path, alert: "Please select date range"
    end
  end
end

app/controllers/accounting/journal_book_controller.rb
class Accounting::JournalBookController < ApplicationController
  def index
  end

  def pdf
    if params[:date_from].present? && params[:date_to].present?
      journal_vouchers = Accounting::Journal.where(post_date: params[:date_from].to_date..params[:date_to].to_date, status: :posted)

      if journal_vouchers.present?
        Accounting::Journal.journal_book_pdf(current_user.userable.id, params[:date_from], params[:date_to], "journal_book")

        redirect_to accounting_journal_book_index_path, notice: "Report is being generated. Please wait for a moment."
      else
        redirect_to accounting_journal_book_index_path, alert: "No journal vouchers found"
      end
    else
      redirect_to accounting_journal_book_index_path, alert: "Please select date range"
    end
  end
end

app/controllers/accounting/receipt_book_controller.rb
class Accounting::ReceiptBookController < ApplicationController
  def index
  end

  def pdf
    if params[:date_from].present? && params[:date_to].present?
      receipts = Treasury::CashierEntry.where(or_date: params[:date_from].to_date..params[:date_to].to_date, status: :posted)

      if receipts.present?
        Treasury::CashierEntry.receipt_book_pdf(current_user.userable.id, params[:date_from], params[:date_to], "receipt_book")

        redirect_to accounting_receipt_book_index_path, notice: "Report is being generated. Please wait for a moment."
      else
        redirect_to accounting_receipt_book_index_path, alert: "No ORs found"
      end
    else
      redirect_to accounting_receipt_book_index_path, alert: "Please select date range"
    end
  end
end

app/views/accounting/checks/_business_checks.html.erb
<div class="p-3">

  <% if current_user.is_treasurer? && !voucher.cancelled? && !voucher.claimable? %>
    <div class="mb-3 <%= flex_justify_align('between') %>">
      <%= link_to new_accounting_check_business_path(voucher), class: small_btn('primary'), data: {turbo_frame: 'modal'} do %>
        <i class="bi bi-plus-lg"></i> Add Business Check
      <% end %>

      <% if @claim.present? %>
        <%= link_to claimable_accounting_check_path(voucher), class: small_btn('success'), data: {turbo_confirm: 'Are you sure?', turbo_method: :get} do %>
          Ready for claim
        <% end %>
      <% end %>
    </div>

  <% end %>

  <table class="table table-bordered table-hover bg-white">
    <thead style="border-bottom: 10px;">
      <tr>
        <th class="text-center" style="width: 120px">Date</th>
        <th class="text-center" style="width: 120px">Check No.</th>
        <th class="text-center">Payee</th>
        <th class="text-center">Type</th>
        <th class="text-center">Amount</th>
        <th class="text-center">Status</th>

        <% if current_user.is_treasurer? && !voucher.claimable?  %>
          <th style="width: 90px"></th>
        <% end %>      </tr>
    </thead>
    <tbody>
      <% if business_checks.present? %>
        <% business_checks.each do |check| %>
          <tr>
            <td class='text-center' ><%= month_day_year check.check_date %></td>
            <td class='text-center' >
              <%= check.check_number %>
            </td>
            <td><%= check.payee %></td>
            <td class='text-center'><%= check.check_type&.humanize %></td>
            <td class="text-end"><%= to_curr check.amount %></td>
            <td class="text-center"><span class="<%= check.decorate.check_badge %>"><%= check.decorate.check_text %></span></td>
            <% if !voucher.cancelled? && current_user.is_treasurer? && !voucher.claimable? %>
              <td class="text-center">
                <%= link_to edit_accounting_check_business_path(voucher, check), 
                  class: small_btn('outline-primary'), 
                  title: 'Edit check', data: {turbo_frame: 'modal'} do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
                <%= link_to accounting_check_business_path(voucher, check), 
                  class: small_btn('outline-danger'), 
                  title: 'Remove check',
                  data: {turbo_confirm: 'Remove check?', turbo_method: :delete} do %>
                  <i class="bi bi-trash"></i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4" class="text-center">No business check yet.</td>
        </tr>
      <% end %>
    </tbody>

    <% if business_checks.present? %>
      <tfoot>
        <tr>
          <th class="text-end" colspan="<%= current_user.is_treasurer? && !voucher.claimable? ? '4' : '4' %>">Total</th>
          <th class="text-end"><%= to_curr voucher.business_checks.sum(:amount) %></th>
        </tr>
      </tfoot>
    <% end %>
  </table>
</div>

app/views/accounting/checks/_form.html.erb
<%= simple_form_for(check, url: params[:rid].present? ? accounting_checks_path(rid: params[:rid]) : '') do |f| %>
  <div class="form-inputs mb-3">
    <div class="row">
      <div class="col-7">
        <%= f.input :date_voucher, as: :string, input_html: {data: {
          controller: "flatpickr",
          flatpickr_max_date: Date.today,
          flatpickr_next_arrow: "Next",
          flatpickr_prev_arrow: "Prev"}
          }, label: 'Voucher date', 
          error: '*Required'
        %>
      </div>
      <div class="col-5">
        <label class="form-label integer required" for="accounting_check_voucher">Voucher <abbr title="required">*</abbr></label>
        <div class="input-group mb-3">
          <span class="input-group-text">CV</span>
          <%= f.input :voucher, wrapper: false, label: false, placeholder: '00000', error: '*Required' %>
        </div>
      </div>
    </div>

    <% if params[:rid].present? %>
      <%= f.label 'Payee', class: 'mb-1' %>
      <%= f.select :global_payable, [[@coop.name, @coop.to_global_id]], {}, { class: 'form-control mb-3', readonly: true } %>
    <% else %>
      <%= f.input :global_payable, 
        collection: @payables, 
        label_method: :to_s, 
        value_method: :to_global_id, 
        label: 'Payee', 
        error: '*Required',
        input_html: {data: {controller: 'ts--select'}}
      %>
    <% end %>
    <%= f.association :treasury_account, collection: Treasury::Account.child_accounts, label: 'Bank', error: '*Required', input_html: {data: {controller: 'ts--select'}} %>
    <div class="row">
      <div class="col-6">
        <% if params[:rid].present? %>
          <%= f.input :amount, error: '*Required', input_html: {readonly: true  } %>
        <% else %>
          <%= f.input :amount, error: '*Required' %>
        <% end %>
      </div>
    </div>
    <%= f.input :particulars, error: '*Required' %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, 'Create Check Voucher', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounting/checks/index.html.erb
<div class="<%= flex_justify_align('', 'center') %> gap-1 mb-3">
  <%= content_tag :h4, "Check Vouchers", class: 'text-primary mb-0' %>
  <%= link_to new_accounting_check_path, class: 'btn btn-sm btn-outline-primary', data: {turbo_frame: 'modal'} do %>
    <i class="bi bi-plus-lg"></i>
  <% end %>
</div>

<div class="<%= flex_justify_align('between','center') %> gap-3 mb-3">   
  <div class="d-flex gap-1">
    <%= search_form_for @q do |f| %>
      <div class="d-flex gap-1">
        <%= f.text_field :payable_of_Cooperative_type_name_or_voucher_cont, class: 'form-control filter_field', placeholder: 'Search voucher or payee' %>
        <%= button_tag(type: 'submit', class: "#{small_btn('warning text-dark')} filter_btn", value: 'branches', style: 'width: 40px') do %>
          <i class='bi bi-search'></i>
        <% end %>
      </div>
    <% end %>

    <%= link_to accounting_checks_path, class: "btn-sm btn btn-secondary filter_btn", title: "Reload" do %>
      <i class="bi bi-arrow-clockwise"></i>
    <% end %>

    
  </div>
  <div class="d-flex gap-1">
    <%= render 'accounting/shared/date_filter', url: accounting_checks_path, req_type: nil %>
    <%= render 'shared/filter_btn' do %>
      <li><%= link_to "All", accounting_checks_path, class: "dropdown-item" %></li>
      <li><%= link_to "Posted", accounting_checks_path(status: "posted", date_from: params[:date_from], date_to: params[:date_to]), class: "dropdown-item" %></li>
      <li><%= link_to "For Approval", accounting_checks_path(status: "for_approval", date_from: params[:date_from], date_to: params[:date_to]), class: "dropdown-item" %></li>
      <li><%= link_to "Pending", accounting_checks_path(status: "pending", date_from: params[:date_from], date_to: params[:date_to]), class: "dropdown-item" %></li>
      <li><%= link_to "Cancelled", accounting_checks_path(status: "cancelled", date_from: params[:date_from], date_to: params[:date_to]), class: "dropdown-item" %></li>
    <% end %>
  </div>
</div>
<table class="<%= table_sm_hoverable %>">
  <thead class="table-dark">
    <tr>
      <th class="text-center" style="min-width: 50px">Voucher</th>
      <th class="text-center" style="min-width: 100px">Date</th>
      <th>Payee</th>
      <th class="text-center">Created by</th>
      <th class="text-center">Amount</th>
      <th class="text-center">Status</th>
    </tr>
  </thead>

  <tbody>
    <% if @vouchers.present? %>
      <% @vouchers.each do |check| %>
        <tr>
          <td class="text-center">
            <%= link_to "#{check.voucher}", check, class: 'text-primary', title: 'View'%>
          </td>
          <td class="text-center"><%= month_day_year(check.date_voucher) %></td>
          <td><%= check.payable.name %></td>
          <td class="<%= centered_cell %>"><%= check.employee %></td>
          <td class="<%= centered_cell %>"><%= to_curr(check.amount) %></td>
          <td class="text-center">
            <span class="<%= check.decorate.status_badge %>"><%= check.status.titleize %></span>
          </td>          
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="7" class="text-center">No check vouchers found.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mb-3">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/accounting/checks/show.html.erb
<% if current_user.is_accountant? %>
  <div class="mb-1">
    <% if @request.present? %>
      <%= link_to accounting_voucher_request_path(@request, pt: @request.payment_type), class: small_btn("secondary") do %>
        <i class="bi bi-chevron-left"></i>
      <% end %>
    <% else %>
      <%= link_to accounting_checks_path, class: small_btn("secondary") do %>
        <i class="bi bi-chevron-left"></i>
      <% end %>
    <% end %>

    <% if @check.posted? %>
      <%= link_to print_accounting_check_path(@check, format: :pdf), class: small_btn('outline-primary'), target: '_blank', title: 'Print' do %>
        <i class="bi bi-printer"></i>
      <% end %>
      <%= link_to download_accounting_check_path(@check, format: :pdf), class: small_btn('outline-primary'), target: '_blank', title: 'Download' do %>
        <i class="bi bi-filetype-pdf"></i>
      <% end %>
    <% end %>
  </div>
  
<% elsif current_user.is_auditor? %>
  <div class="mb-1">
    <%= link_to audit_for_audits_path, class: small_btn("secondary"), title: 'Back' do %>
      <i class="bi bi-chevron-left"></i>
    <% end %>
    <%= link_to "MOA", show_details_agreement_path(@check.voucher_request.requestable.agreement), class: small_btn('outline-primary'), title: "Voucher", target: "_blank" %>
    <%= link_to "Claim details", claim_process_claims_process_claim_path(@check.voucher_request.requestable), class: small_btn('outline-primary'), title: "Claim Details", target: "_blank" %>
    <% unless @check.approved? %>
      <%=  link_to approve_audit_for_audit_path(@check, e_t: @check.entry_type), class: small_btn('success'), data: {turbo_confirm: "Finish audit and approve voucher?", turbo_method: :get} do  %>
        <i class="bi bi-check-circle-fill"></i> Approve
      <% end %>
      <%=  link_to new_accounting_check_remark_path(@check, e_t: @check.entry_type, audit: true), data: {turbo_frame: 'reg_form_modal' }, class: 'btn btn-sm btn-warning', title: 'Pending Voucher' do %>
        <i class="bi bi-hourglass-split"></i> Pending
      <% end %>
    <% end %>
    <% if @check.remarks.present? %>
      <%= link_to accounting_check_remarks_path(@check, e_t: @check.entry_type, audit: true), class: 'btn btn-sm btn-danger', data: {turbo_frame: 'reg_form_modal'} do %>
        <i class="bi bi-card-list"></i> Remarks
      <% end %>
    <% end %>
  </div>
<% end %>

<%= render @check %>

<div class="card">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <% if current_user.is_accountant? || current_user.is_auditor? %>
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="ledger-tab" data-bs-toggle="tab" data-bs-target="#ledger" type="button" role="tab" aria-controls="ledger" aria-selected="true">Ledger</button>
      </li>
    <% end %>

    <li class="nav-item" role="presentation">
      <button class="nav-link" id="check-tab" data-bs-toggle="tab" data-bs-target="#check" type="button" role="tab" aria-controls="check" aria-selected="false">Business Checks</button>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">

    <% if current_user.is_accountant? || current_user.is_auditor? %>
      <div class="tab-pane fade show active" id="ledger" role="tabpanel" aria-labelledby="ledger-tab">
        <%= render 'payments/entries/ledger', ledgers: @ledgers, entry: @check  %>
      </div>
    <% end %>

    <div class="tab-pane fade <%= 'show active' if current_user.is_treasurer? %>" id="check" role="tabpanel" aria-labelledby="check-tab">
      <%= render 'business_checks', business_checks: @business_checks, voucher: @check %>
    </div>
  </div>
</div>